AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Lambda - This Lambda finds negative Holiday Suspension invoices and converts them to be a credit on the user's account so that the amount is discounted off their next positive bill"
Parameters:
    Stack:
        Description: Stack name
        Type: String
        Default: Subscriptions
    App:
        Description: Application name
        Type: String
        Default: zuora-holiday-suspension-invoice-crediter
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - PROD
            - UAT
        Default: UAT

Resources:
    Zuora-holiday-suspension-invoice-crediter-Role:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                             - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /
            Policies:
                - PolicyName: LambdaPolicy
                  PolicyDocument:
                      Statement:
                          - Effect: Allow
                            Action:
                                - logs:CreateLogGroup
                                - logs:CreateLogStream
                                - logs:PutLogEvents
                                - lambda:InvokeFunction
                            Resource: "*"

    Lambda:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName:
                !Sub zuora-holiday-suspension-invoice-crediter-${Stage}
            Environment:
                Variables:
                # Add your config/environment variables here.

            Code:
                S3Bucket: Subscriptions-dist
                S3Key:
                    !Sub ${Stack}/${Stage}/zuora-holiday-suspension-invoice-crediter/zuora-holiday-suspension-invoice-crediter.zip
            Description: This Lambda finds negative Holiday Suspension invoices and converts them to be a credit on the user's account so that the amount is discounted off their next positive bill"
            Handler: com.gu.zuora-holiday-suspension-invoice-crediter.Lambda::handleRequest
            MemorySize: 256
            Role:
                Fn::GetAtt:
                - Zuora-holiday-suspension-invoice-crediter-Role
                - Arn
            Runtime: java8
            Timeout: 300

    #
    # Add your Lambda trigger rule and permissions here.
    #
    #
    #
