AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Lambda - This Lambda finds negative Holiday Suspension invoices and converts them to be a credit on the user's account so that the amount is discounted off their next positive bill"
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: Subscriptions
  App:
    Description: Application name
    Type: String
    Default: Zuora-Holiday-Suspension-Invoice-Crediter
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - UAT
    Default: UAT

Resources:
  Zuora-Holiday-Suspension-Invoice-Crediter-Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
               - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        !Sub Zuora-Holiday-Suspension-Invoice-Crediter-${Stage}
      Environment:
        Variables:
          - ZuoraApiAccessKeyId:
          - ZuoraApiSecretAccessKey:
          - ZuoraApiHost:
      Code:
        S3Bucket: Subscriptions-dist
        S3Key:
          !Sub ${Stack}/${Stage}/zuora-holiday-suspension-invoice-crediter/zuora-holiday-suspension-invoice-crediter.zip
      Description: This Lambda finds negative Holiday Suspension invoices and converts them to be a credit on the customer's account so that the amount is deducted off their next positive bill.
      Handler: com.gu.zuora.crediter.holidaysuspension.Lambda::handleRequest
      MemorySize: 256
      Role:
        Ref: Zuora-Holiday-Suspension-Invoice-Crediter-Role
      Runtime: java8
      Timeout: 60
